formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
  file:
    backupCount: 6
    class: logginghandlers.timedrotatingfilesmtphandler.TimedRotatingFileSMTPHandler
    configfilename: config.ini
    filename: log/alarmmonitor.log
    formatter: simple
    level: DEBUG
    send_log: false
    when: midnight
  mail:
    class: logginghandlers.smtperrorhandler.SMTPErrorHandler
    configfilename: config.ini
    formatter: simple
    level: DEBUG
root:
  handlers:
  - console
  - file
  - mail
  level: DEBUG
version: 1
